build:
	make -C c
	make -C native/NativeC
	make -C native/NativeCPP
	make -C native/NativeFortran

clean:
	make -C c clean
	make -C native/NativeC clean
	make -C native/NativeCPP clean
	make -C native/NativeFortran clean
