name: Benchmark

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:
    inputs:
      samples:
        type: number
        required: true
        default: '10'
      nfe:
        type: number
        required: true
        default: '100000'
      java-distribution:
        type: choice
        required: true
        description: Java distribution
        options:
          - 'zulu'
          - 'temurin'
          - 'oracle'
        default: 'zulu'
      java-version:
        type: choice
        required: true
        description: Java version
        options:
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
        default: '17'
        
env:
  SAMPLES: ${{ inputs.samples || '10' }}
  NFE: ${{ inputs.nfe || '100000' }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-13 ]
    steps:
      - name: Setup build
        uses: MOEAFramework/.github/actions/setup-build@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          setup-python: true
          python-version: '3.12'
      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10' 
      - uses: fortran-lang/setup-fortran@v1
        if: runner.os == 'macOS'
        with:
          compiler: gcc
          version: 13
      - name: Build
        run: make clean build
      - name: Run Benchmarks
        run: make SAMPLES=${{ env.SAMPLES }} NFE=${{ env.NFE }} benchmark
