name: Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:
    inputs:
      java-distribution:
        type: choice
        required: true
        description: Java distribution
        options:
          - 'zulu'
          - 'temurin'
          - 'oracle'
        default: 'zulu'
      java-version:
        type: choice
        required: true
        description: Java version
        options:
          - '19'
          - '20'
          - '21'
          - '22'
        default: '19'
        
jobs:
  maven-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup build
      uses: MOEAFramework/.github/actions/setup-build@main
      with:
        java-version: ${{ inputs.java-version || '19' }}
        java-distribution: ${{ inputs.java-distribution }}
    - name: Run tests
      run: mvn test
    
